### ISSUE TITLE
http error 500 after partial result

### ISSUE THREAD

**Issue by frisbee23** [swayf/proxmoxer#32]
hi, 
im using backend openssh, let proxmoxer connect to a server, and call for example /nodes (also tryed other urls with same result); i get the data of the proxmox-node im connected too, but after that i get 500 internal server error. 

i think somehow proxmoxer or something on the node is trying to connect to the other nodes, and fails. but thats just a theory. 

here is some output; i'm using proxmox-deploy which is a small tool also hosted on github.

$ proxmox-deploy
2017-05-03 22:33:33,003 INFO:proxmoxdeploy.cli: proxmox-deploy version 0.3 (build 7b45fa9) starting...
proxmox-deploy version 0.3 (build 7b45fa9) starting...
2017-05-03 22:33:33,014 INFO:proxmoxdeploy.cli: Asking user for configuration input
Asking user for configuration input
2017-05-03 22:33:33,014 DEBUG:proxmoxdeploy.proxmox: XXXX
XXXX
2017-05-03 22:33:33,015 INFO:proxmoxer.core: GET /nodes/pvehost01/storage
GET /nodes/pvehost01/storage
2017-05-03 22:33:38,915 DEBUG:proxmoxer.core: Status code: 500, output: [
   {
      "active" : 1,
      "avail" : 32243920896,
      "content" : "iso,images,rootdir,vztmpl",
      "shared" : 0,
      "storage" : "local",
      "total" : 101327663104,
      "type" : "dir",
      "used" : 63913005056
   }
]
Status code: 500, output: [
   {
      "active" : 1,
      "avail" : 32243920896,
      "content" : "iso,images,rootdir,vztmpl",
      "shared" : 0,
      "storage" : "local",
      "total" : 101327663104,
      "type" : "dir",
      "used" : 63913005056
   }
]
Traceback (most recent call last):
  File "/home/pknoll/proxmox-deploy/run.py", line 10, in <module>
    sys.exit(main())
  File "/home/pknoll/proxmox-deploy/proxmoxdeploy/cli.py", line 99, in main
    (proxmox, cloudinit) = interact_with_user(args, api)
  File "/home/pknoll/proxmox-deploy/proxmoxdeploy/cli.py", line 83, in interact_with_user
    proxmox_answers = ask_proxmox_questions(api)
  File "/home/pknoll/proxmox-deploy/proxmoxdeploy/proxmox.py", line 64, in ask_proxmox_questions
    available_storage = proxmox.get_storage(chosen_node)
  File "/home/pknoll/proxmox-deploy/proxmoxdeploy/proxmox.py", line 186, in get_storage
    for storage in self.client.nodes(node).storage.get():
  File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 84, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 79, in _request
    raise ResourceException("{0} {1}".format(resp.status_code, httplib.responses[resp.status_code]))
proxmoxer.core.ResourceException: 500 Internal Server Error

pknoll@docker-mgmt-01:/usr/local/lib/python2.7/dist-packages/proxmoxer$ cat __init__.py
__author__ = 'Oleg Butovich'
__copyright__ = '(c) Oleg Butovich 2013-2017'
__version__ = '0.2.5'

proxmox Virtual Environment 4.4-13/7ea56165

im happy to add more details if needed.

did you ever come across something like this? is it maybe a known thing and im just not googleing well enough?

thankfull for any pointers,
cheers,
fil

**Comment by swayf** [comment]
I think it should work in 1.0.0

**Comment by gustavovalverde** [comment]
I'm having this same issue on the latest version with proxmox version 5.2
