### ISSUE TITLE
Problems with version 5.3

### ISSUE THREAD

**Issue by shibumi** [swayf/proxmoxer#67]
Hi,
I get with the newest proxmox version the following errors:
```
Traceback (most recent call last):
  File "/root/proxmox-dokuwiki-exporter.py", line 27, in <module>
    for node in proxmox.nodes.get():
  File "/root/.local/lib/python3.5/site-packages/proxmoxer/core.py", line 84, in get
    return self(args)._request("GET", params=params)
  File "/root/.local/lib/python3.5/site-packages/proxmoxer/core.py", line 79, in _request
    resp.content))
proxmoxer.core.ResourceException: 500 Internal Server Error: 
```

As message In the server error I get a full graph of my cluster (here redacted). what the hell?!

The line that triggers this error is this one here: `for node in proxmox.nodes.get():`

**Comment by pskrzyns** [comment]
@shibumi new version of pvesh has a few changes:
* by default it returns ACII text instead of json (you need to add --format-output json to make it work as before)
* if request is correct it doesn't return response code which is exptected by proxmoxer (resulting with 500 internal error)
working on fix for that

**Comment by shibumi** [comment]
@pskrzyns i use `proxmoxer` as library for my own script. No idea where I should include this `--format-output json`..
