### ISSUE TITLE
how i can creeate VM with api ?

### ISSUE THREAD

**Issue by houcinedz** [swayf/proxmoxer#73]

**Comment by elschman** [comment]
Simple..
first install the proxmoxer
seconf follow the guideline to open a session
open https://pve.proxmox.com/pve-docs/api-viewer/index.html to get knowledge about the api apth.
I guess nodes /api2/json/nodes/{node}/qemu is the one your looking for
create the api call out of this
proxmox.nodes([TARGETnode]).qemu.push(vmid=[newID])

newID must be a free one.

**Comment by houcinedz** [comment]
whene i try to run this code i have proble 
```
> from proxmoxer import ProxmoxAPI
> proxmox = ProxmoxAPI('****', user='*****',password='****', verify_ssl=False)
> 
> for node in proxmox.nodes.get():
>     for vm in proxmox.nodes(node['node']).openvz.get():
>         print "{0}. {1} => {2}" .format(vm['vmid'], vm['name'], vm['status'])
```


### Traceback (most recent call last):
  File "create.py", line 2, in <module>
    proxmox = ProxmoxAPI('https://***/', user='***',password='***', verify_ssl=False)
  File "C:\Users\power\Desktop\PY\proxmoxer\proxmoxer\core.py", line 106, in __init__
    self._backend = importlib.import_module('.backends.%s' % backend, 'proxmoxer').Backend(host, **kwargs)
  File "C:\Users\power\Desktop\PY\proxmoxer\proxmoxer\backends\https.py", line 117, in __init__
    host, host_port = host.split(':')
ValueError: too many values to unpack

**Comment by houcinedz** [comment]
how i can create a ProxmoxAPI

**Comment by elschman** [comment]
proxmox = ProxmoxAPI('https:///', user='',password='***', verify_ssl=False)

It looks like you forgot to mention the node you want to use to manage the proxmox.

proxmox = ProxmoxAPI('https://[PROXMOXNODE]/', user='',password='***', verify_ssl=False)

**Comment by houcinedz** [comment]
ip addresse ? 

> https://@:port/ 
that's all ??

**Comment by houcinedz** [comment]
https://@:port/
that's all ?

**Comment by elschman** [comment]
See the main page at 

> Short usage information

**Comment by houcinedz** [comment]
how i can create VM with proxmoxer ?
