### ISSUE TITLE
boolean parameter not serialized correctly

### ISSUE THREAD

**Issue by J4RF** [swayf/proxmoxer#89]
```
prox.nodes('pve1').lxc(500).clone.create(newid=501, full=True, hostname="worker1", pool="workers")
```

results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/proxmoxer/core.py", line 181, in create
    return self.post(*args, **data)
  File "/usr/local/lib/python3.8/site-packages/proxmoxer/core.py", line 172, in post
    return self(args)._request("POST", data=data)
  File "/usr/local/lib/python3.8/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 400 Bad Request: Parameter verification failed. - {'full': "type check ('boolean') failed - got 'True'"}
```

**Comment by J4RF** [comment]
Not a proxmoxer issue, happening with the bare API as well. Closing

**Comment by J4RF** [comment]
For posterity, this was resolved by passing in 1 instead of True. Proxmox API accepts the following string values for booleans: `0, 1, on, off, yes, no, true, false`
